### ISSUE TITLE
Extension only works once

### ISSUE THREAD

**Issue by galaxystg** [vladmandic/sd-extension-steps-animation#12]
Hi, I'm getting this error
Steps animation warning: postprocess early call {'current': 0, 'target': 150}
Save animation error: framerate is zero
The first time it works fine, but then no matter what I change, it just gives me this error. Only works again if I uninstall from the extension folder and reinstall it (but it does the same, first animation fine then this error).
Also I checked the code and it isn't the steps because I tried 2 steps and it's the same. However, if it's relevant I'm using PLMS sampler

**Comment by vladmandic** [comment]
the problem is that built-in schedulers in from original stable-diffusion such as PLMS and DDIM do not trigger callbacks in WebUI at all, so there is no hook for a script. I've added a note on that in the code and in the readme, but not much I can do about it.
