### ISSUE TITLE
Unrecognized option 'preset'. Error splitting the argument list: Option not found

### ISSUE THREAD

**Issue by catalpaaa** [vladmandic/sd-extension-steps-animation#15]
>   "prompt": "best quality ultra high res ultra detailed masterpiece photorealistic14",
  "negative": "bad prompt08  deepnegative  easynegative watermark photograph by bad artist",
  "seed": 4023858024,
  "sampler": "DPM++ SDE Karras",
  "cfgscale": 7,
  "steps": 3,
  "current": 3,
  "skip": 0,
  "info": "best quality ultra high res ultra detailed masterpiece photorealistic14, Negative prompt  bad prompt08  deepnegative  easynegative watermark photograph by bad artist, Steps 3 Sampler DPM SDE Karras CFG scale 7 Seed 4023858024 Size 512x768 Model hash 7234b76e42 Model Chillout MixchilloutmixNi",
  "model": "Chillout",
  "embedding": "none",
  "faces": null,
  "timestamp": "20230302225138",
  "inpath": "outputs/txt2img-images/intermediate",
  "outpath": "outputs/txt2img-images/animation",
  "codec": "libx265",
  "duration": 10,
  "interpolation": "mci",
  "loglevel": "info",
  "cli": "ffmpeg -hide_banner -loglevel {loglevel} -hwaccel auto -y -framerate {framerate} -i \"{inpath}/%5d.jpg\" -r {videorate} {preset} {minterpolate} {flags} -metadata title=\"{description}\" -metadata description=\"{info}\" -metadata author=\"stable-diffusion\" -metadata album_artist=\"{author}\" \"{outfile}\"",
  "framerate": 0.3,
  "videorate": 30,
  "author": "https://github.com/vladmandic",
  "preset": "-vcodec libx265 -preset faster -crf 28",
  "flags": "-movflags +faststart",
  "ffmpeg": "/home/catalpa/anaconda3/envs/stable-diffusion/bin/ffmpeg",
  "minterpolate": "-vf minterpolate=mi_mode=mci,fifo",
  "outfile": "outputs/txt2img-images/animation/4023858024-best quality ultra high res ultra detailed masterpiece photorealistic14.mp4",
  "description": "best quality ultra high res ultra detailed masterpiece photorealistic14 | negative bad prompt08  deepnegative  easynegative watermark photograph by bad artist | seed 4023858024 | sampler DPM++ SDE Karras | cfgscale 7 | steps 3 | current 3 | model Chillout | embedding none | faces None | timestamp 20230302225138 | interpolation mci"
}
Steps animation creating movie sequence: outputs/txt2img-images/animation/4023858024-best quality ultra high res ultra detailed masterpiece photorealistic14.mp4 images: 3
Steps animation CMD: ffmpeg -hide_banner -loglevel info -hwaccel auto -y -framerate 0.3 -i "outputs/txt2img-images/intermediate/%5d.jpg" -r 30 -vcodec libx265 -preset faster -crf 28 -vf minterpolate=mi_mode=mci,fifo -movflags +faststart -metadata title="best quality ultra high res ultra detailed masterpiece photorealistic14 | negative bad prompt08  deepnegative  easynegative watermark photograph by bad artist | seed 4023858024 | sampler DPM++ SDE Karras | cfgscale 7 | steps 3 | current 3 | model Chillout | embedding none | faces None | timestamp 20230302225138 | interpolation mci" -metadata description="best quality ultra high res ultra detailed masterpiece photorealistic14, Negative prompt  bad prompt08  deepnegative  easynegative watermark photograph by bad artist, Steps 3 Sampler DPM SDE Karras CFG scale 7 Seed 4023858024 Size 512x768 Model hash 7234b76e42 Model Chillout MixchilloutmixNi" -metadata author="stable-diffusion" -metadata album_artist="https://github.com/vladmandic" "outputs/txt2img-images/animation/4023858024-best quality ultra high res ultra detailed masterpiece photorealistic14.mp4"
Unrecognized option 'preset'.
Error splitting the argument list: Option not found
Steps animation removing 3 files from temp folder: outputs/txt2img-images/intermediate

**Comment by vladmandic** [comment]
your version of `ffmpeg` does not support selected codec `x265`, either update your version of ffmpeg or try with a different codec.

i've added codec check in <https://github.com/vladmandic/sd-extension-steps-animation/commit/ee270d3e69c4c7d46bb7e1edd7a537e7efd76b35> to better report errors like this.
