### ISSUE TITLE
Batch count

### ISSUE THREAD

**Issue by juans98020** [vladmandic/sd-extension-steps-animation#17]
if I put more than 2 in the batch count the final video comes out with just one image.

**Comment by vladmandic** [comment]
each batch is a separate seed, so supporting batch sizes larger than one would mean creating multiple videos - is that really desired?

if yes, i can add support for that.

**Comment by juans98020** [comment]
yes, I don't know if you have updated anything, but before, when I put a batch count higher than 2, it would create the video normally with both images, now it only creates one.

**Comment by vladmandic** [comment]
yes, previously it would create video with both images, but since they are different images, that's not really correct.
so i've limited it to first image in batch. i can add support for higher batch sizes, but what is the desired result?

**Comment by juans98020** [comment]
I think it would be good to have an option to create separate videos, for example if I put 4 batch count or size it will create 4 separate videos in the folder

**Comment by vladmandic** [comment]
ok, i've added support for higher batch sizes.

**Comment by juans98020** [comment]
The same thing keeps happening, if I create more than one image the video is created, but only with the first image that SD generated instead of both images in the same video.

**Comment by juans98020** [comment]
I noticed that this occurs in the batch count and not in the batch size, you can do the same thing in the batch count?

**Comment by vladmandic** [comment]
i've just added support for batch count (batch size support was added yesterday)
