### ISSUE TITLE
video not playable on all codeces

### ISSUE THREAD

**Issue by catalpaaa** [vladmandic/sd-extension-steps-animation#18]
attempt to play it will show
![image](https://user-images.githubusercontent.com/89681913/231691495-ec29091a-56e8-498b-85f1-a0cb8889a476.png)
or a black screen on some video player

**Comment by catalpaaa** [comment]
note that if i drag the file into desktop chrome then its playable there, but not on ios devices

**Comment by vladmandic** [comment]
i'll take a look at presets.

**Comment by catalpaaa** [comment]
> i'll take a look at presets.

thanks, is there a way to change the default settings of say the codecs used or the save directory

**Comment by vladmandic** [comment]
not via config, you can edit the source file: <https://github.com/vladmandic/sd-extension-steps-animation/blob/0c7e93583265eca6e766f81d1ce85ddb39f7636d/scripts/steps_animation.py#L30>

**Comment by catalpaaa** [comment]
> not via config, you can edit the source file: <https://github.com/vladmandic/sd-extension-steps-animation/blob/0c7e93583265eca6e766f81d1ce85ddb39f7636d/scripts/steps_animation.py#L30>

I tried to edit the value of gr.textbox but somehow after rebooting webui the default directory still doesn't change.

Can you look into that

**Comment by vladmandic** [comment]
textbox with presets is not designed to save config. that would be a feature request and not sure if its worth it. my goal is to have presets that are good-enough for 99% of users.

**Comment by catalpaaa** [comment]
> textbox with presets is not designed to save config. that would be a feature request and not sure if its worth it. my goal is to have presets that are good-enough for 99% of users.

Thanks.

Maybe is me but changing non of the values in ui() makes different in webui

**Comment by angrysky56** [comment]
> attempt to play it will show ![image](https://user-images.githubusercontent.com/89681913/231691495-ec29091a-56e8-498b-85f1-a0cb8889a476.png) or a black screen on some video player

I changed my settings setting "File format for images" from png to jpg and it worked.
