### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ronbere** [vladmandic/sd-extension-steps-animation#20]
nothing appears on intermediate and animation folders. ffmpeg installed, deforum working

**Comment by vladmandic** [comment]
i'll check, but how about you go back and set proper title and fill issue template.

**Comment by ronbere** [comment]
Steps animation error: ffmpeg not found

**Comment by vladmandic** [comment]
which os? can you post console log?

**Comment by vladmandic** [comment]
are you sure that ffmpeg is in path? if its installed, that's a typical problem in 99% of cases.
lets see if python can find it - try to execute:
> python -c 'import shutil; print(shutil.which("ffmpeg"))'

**Comment by ronbere** [comment]
>>> python -c 'import shutil; print(shutil.which("ffmpeg"))'
  File "<stdin>", line 1
    python -c 'import shutil; print(shutil.which("ffmpeg"))'
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax

Sorry i'm not an expert of python

**Comment by vladmandic** [comment]
just run in command line, don't start python.

**Comment by ronbere** [comment]
Working fine on A1111...

**Comment by vladmandic** [comment]
the syntax i asked you to run was not valid for windows, try again using this:
> python -c "import shutil; print(shutil.which(\"ffmpeg\"))"

**Comment by LanceGao97** [comment]
![1231231](https://user-images.githubusercontent.com/125782753/234812959-85ea0f56-ef69-46f6-b25f-e851c2908ab6.jpg)

**Comment by LanceGao97** [comment]
sorry i don't know any coding , but i think the webui don't know what that path means, 
outputs/txt2img-images\\animation\\1979887629-realisticmasterpiecefull renderdetailedmotoko.mp4"', 'returncode': 1}
Steps animation output At least one output file must be specified
it has   \ and //

**Comment by LanceGao97** [comment]
> nothing appears on intermediate and animation folders. ffmpeg installed, deforum working

the intermedia will be deleted by default checkbox  (the creator must be a clean man) !  if you uncheck delete intermedia,  you will see the sequence images, 
and the script has some issue with windows path, so the ffmpeg can't creat that video file, maybe the naming is too long,
so both the intermedia and video is not existing.    （-_-）
