### ISSUE TITLE
possible file wiper bug

### ISSUE THREAD

**Issue by moonshinegloss** [vladmandic/sd-extension-steps-animation#21]
a users output folder files got wiped using this plugin, this is my best guess as to why after looking at the code:

- user sets output folder to same as their regular image outputs of webui
- leaves "intermediate" textbox empty (hence any path join on tmp_path resolves to the output folder)
- now when the script goes to delete the intermediate folder at the end, it will wipe the entire folder worth of images instead

**Comment by vladmandic** [comment]
fixed.
