### ISSUE TITLE
The intermediate do exist , but the animation don't exist

### ISSUE THREAD

**Issue by LanceGao97** [vladmandic/sd-extension-steps-animation#23]
The function is very nice, I searched everywhere , only here has this animation steps function, I just hope it works nicely, and the file name and file path might need some adjustment for using.

**Comment by LanceGao97** [comment]
the intermediates are fine and do exist,  but
last night I tested it , it created my first animation, it is fine, but today,  no matter what I do, the intermediates does refreshes and are new images, which looks normal, but the animation folder only have a single file of my last night test,  the new animation is not created, and no any warning or tips!
Win10 , CMD input ffmpeg， it shows the version of the ffmpeg,

**Comment by LanceGao97** [comment]
is it possible that the code can only creat one animation file?

**Comment by LanceGao97** [comment]
the cmd window  , last line shows  steps animation output at least one output file must be specified,

**Comment by LanceGao97** [comment]
![1231231](https://user-images.githubusercontent.com/125782753/234813694-24510c9a-dd2c-4471-b3a1-4893ca8a9094.jpg)
sorry i don't know any coding , but i think the webui don't know what that path means,
outputs/txt2img-images\animation\1979887629-realisticmasterpiecefull renderdetailedmotoko.mp4"', 'returncode': 1}
Steps animation output At least one output file must be specified
it has \ and //

**Comment by utak3r** [comment]
There's a pull request open and waiting for approval, which is about issues with paths on Windows.

**Comment by vladmandic** [comment]
updated the repo, can you check?

**Comment by LanceGao97** [comment]
> 

it works, perfectly, THanks

**Comment by LanceGao97** [comment]
> 

the function is nice, and the options are simple, excellent scripting
