### ISSUE TITLE
[Issue]: Link in "Steps animation"-menu leads to 404

### ISSUE THREAD

**Issue by horribleCodes** [vladmandic/sd-extension-steps-animation#25]
### Issue Description

The link found at the top of the "Steps animation"-menu "[Creates animation sequence from denoised intermediate steps with video frame interpolation to achieve desired animation duration](https://github.com/vladmandic/generative-art/tree/main/extensions)" leads to a 404. Is the "generative-art"-repository set to private? Or was this supposed to link to something different?

![image](https://user-images.githubusercontent.com/7748313/236662635-9a39726b-0c4b-4c6d-92f0-7edc836350c6.png)

### Version Platform Description

Version: 22e58809 Sat May 6 08:51:23 2023 -0400
OS: Windows 11
Browser: Brave

**Comment by vladmandic** [comment]
yup, oversight on my part when i changed location of the extension. fixed.
