### ISSUE TITLE
Animation not saving

### ISSUE THREAD

**Issue by thaKnza** [vladmandic/sd-extension-steps-animation#26]
I was able to use this extension last night to create animations, but this morning I boot up my computer and it's suddenly broken. I haven't changed anything about my setup.

In the console, I get this: "Steps animation no interim images were created"

I do have all of the intermediate images in my intermediate folder, but the animation doesn't show up in the animation folder.

**Comment by vladmandic** [comment]
i just made some changes, please try again. and if it fails, run with debug flag and post actual console output here.

**Comment by xyzDist** [comment]
```
  "model": "breakdomain_M2150,",
  "embedding": "none",
  "faces": null,
  "timestamp": "20230520153351",
  "inpath": "outputs/txt2img-images\\intermediate",
  "outpath": "outputs/txt2img-images\\animation",
  "codec": "libx264",
  "duration": 10,
  "last_frame_duration": 1,
  "interpolation": "none",
  "loglevel": "info",
  "cli": "ffmpeg -hide_banner -loglevel {loglevel} -hwaccel auto -y -framerate {framerate} -start_number {sequence} -i \"{inpath}/%7d-{short_name}.{extension}\" -r {videorate}
{preset} {vfilters} {flags} -metadata title=\"{description}\" -metadata description=\"{info}\" -metadata author=\"stable-diffusion\" -metadata album_artist=\"{author}\"
\"{outfile}\"",
  "framerate": 2.0,
  "videorate": 30,
  "author": "https://github.com/vladmandic",
  "preset": "-vcodec libx264 -preset medium -crf 23 -pix_fmt yuv420p",
  "extension": "jpg",
  "short_name": "2303573022-absurdres highres ultra detailed 1girl13 BREAK brutalist art raw concrete geometric forms archit",
  "flags": "-movflags +faststart",
  "ffmpeg": "C:\\Program Files\\ImageMagick-7.0.10-Q16\\ffmpeg.EXE",
  "ffprobe": "C:\\ffmpeg\\bin\\ffprobe.EXE",
  "minterpolate": "",
  "tpad": "tpad=stop_mode=clone:stop_duration=1",
  "vfilters": "-vf tpad=stop_mode=clone:stop_duration=1",
  "outfile": "outputs/txt2img-images\\animation\\2303573022-absurdres highres ultra detailed 1girl13 BREAK brutalist art raw concrete geometric forms archit.mp4",
  "sequence": "0000001",
  "description": "absurdres highres ultra detailed 1girl13, BREAK, brutalist art raw concrete geometric forms architectural sculptures bold textures industrial aesthetic unadorned
surfaces, BREAK, digital painting virtual brushstrokes versatile techniques realistic textures creative freedom modern artistic expression | negative EasyNegative worst quality low
quality14  nsfw  blush13 logo | seed 2303573022 | sampler DPM++ SDE Karras | cfgscale 6.5 | steps 30 | last 20 | model breakdomain_M2150, | embedding none | faces None | timestamp
20230520153351 | interpolation none"
}
Steps animation no interim images were created
```

Hi @vladmandic , here is the debug info output, it save out the intermediate images but no movie convert out.
it does work sometimes. thanks!

**Comment by vladmandic** [comment]
sorry to bug you again,
can you post this exact debug output AND list of files in intermediate folder?
there is something wrong with matching filenames to determine which files should be used for animation, but i cannot reproduce locally so i need to ask you.

**Comment by xyzDist** [comment]
Hi, no worries, thanks for the looking into this, let me do a new output and the list of the images for you.
looks like the image file name too long?

`  "prompt": "photorealistic128kbest quality ultra high res, 1girl asian girl black eyes smile holding a can of pepsi at her head wearing white tank top13 blue jeans simple
background12  thin lips, , , loraadddetail05",
  "negative": "paintings sketches worst quality2 low quality2 lowres monochrome grayscale badhands5",
  "seed": 3162963676,
  "sampler": "DPM++ 2M Karras",
  "cfgscale": 7,
  "steps": 28,
  "laststep": 28,
  "skip": 0,
  "batchsize": 1,
  "batchcount": 1,
  "info": "photorealistic128kbest quality ultra high res, 1girl asian girl black eyes smile holding a can of pepsi at her head wearing white tank top13 blue jeans simple
background12  thin lips, , , loraadddetail05, Negative prompt paintings sketches worst quality2 low quality2 lowres monochrome grayscale badhands5, Steps 28 Sampler DPM 2M Karras
CFG scale 7 Seed 3162963676 Size 846x1024 Model hash ac68270450 Model braBeautifulRealisticbrav5 Clip skip 2 ENSD 1 ControlNet 0 preprocessor lineartanime model
controlv11psd15lineart 43d4be0d weight 1 startingending 0 1 resize mode Just Resize pixel perfect True control mode Balanced preprocessor params 512 64 64 ControlNet 1 preprocessor
softedgehed model controlv11psd15softedge a8575a2a weight 08 startingending 0 1 resize mode Crop and Resize pixel perfect True control mode Balanced preprocessor params 512 100
200",
  "model": "braBeautifulRealistic_brav5,",
  "embedding": "none",
  "faces": null,
  "timestamp": "20230521211049",
  "inpath": "outputs/txt2img-images\\intermediate",
  "outpath": "outputs/txt2img-images\\animation",
  "codec": "libx264",
  "duration": 10,
  "last_frame_duration": 0,
  "interpolation": "none",
  "loglevel": "info",
  "cli": "ffmpeg -hide_banner -loglevel {loglevel} -hwaccel auto -y -framerate {framerate} -start_number {sequence} -i \"{inpath}/%7d-{short_name}.{extension}\" -r {videorate}
{preset} {vfilters} {flags} -metadata title=\"{description}\" -metadata description=\"{info}\" -metadata author=\"stable-diffusion\" -metadata album_artist=\"{author}\"
\"{outfile}\"",
  "framerate": 2.8,
  "videorate": 30,
  "author": "https://github.com/vladmandic",
  "preset": "-vcodec libx264 -preset medium -crf 23 -pix_fmt yuv420p",
  "extension": "jpg",
  "short_name": "3162963676-photorealistic128kbest quality ultra high res 1girl asian girl black eyes smile holding a can of",
  "flags": "-movflags +faststart",
  "ffmpeg": "C:\\Program Files\\ImageMagick-7.0.10-Q16\\ffmpeg.EXE",
  "ffprobe": "C:\\ffmpeg\\bin\\ffprobe.EXE",
  "minterpolate": "",
  "tpad": "",
  "vfilters": "",
  "outfile": "outputs/txt2img-images\\animation\\3162963676-photorealistic128kbest quality ultra high res 1girl asian girl black eyes smile holding a can of..mp4",
  "sequence": "0000001",
  "description": "photorealistic128kbest quality ultra high res, 1girl asian girl black eyes smile holding a can of pepsi at her head wearing white tank top13 blue jeans simple
background12  thin lips, , , loraadddetail05 | negative paintings sketches worst quality2 low quality2 lowres monochrome grayscale badhands5 | seed 3162963676 | sampler DPM++ 2M
Karras | cfgscale 7 | steps 28 | last 28 | model braBeautifulRealistic_brav5, | embedding none | faces None | timestamp 20230521211049 | interpolation none"
}
Steps animation no interim images were created
Total progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:52<00:00,  1.89s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:52<00:00,  1.96s/it]`

![image](https://github.com/vladmandic/sd-extension-steps-animation/assets/126343149/4e34f009-7fa6-48d1-840b-6de676e8fe6b)

**Comment by vladmandic** [comment]
ok, i think i fixed it.
if issue persists, report the same outputs here and i'll reopen.
btw, please upload file list as text as its really hard to do string match from a screenshot :)
