### ISSUE TITLE
Option to change Live Preview Subject

### ISSUE THREAD

**Issue by ChaitanyaKatti** [vladmandic/sd-extension-steps-animation#28]
There is a setting for live preview subject in sd-webui. The default is 'Prompt' and it looks decent when the image is being processed.
The other option 'Combined' shows a lot of color variation/distortion and these images are saved by this extension even when 'Prompt' option is selected.

Is it possible to change the live preview subject for the animation?

Here is a comparison between the two different previews at the same intermediate step:

![comparison](https://github.com/vladmandic/sd-extension-steps-animation/assets/96473570/fc226214-70b4-4cc3-88b9-93906dc13390)

**Comment by vladmandic** [comment]
I'll take a look

**Comment by vladmandic** [comment]
i took a look (few weeks later, somehow this fell under the radar) and this is not something that should be done in the extension.
`live_preview_content` setting is only used within k-diffusers schedulers to store current latent image (before denoising)
so...
a) its not used by default unipc anyhow as that is in different family of schedulers.
b) steps animation extensions calls denoising, but it has no idea on who stored what as last latent image
