### ISSUE TITLE
Very low res output video?

### ISSUE THREAD

**Issue by CodeF53** [vladmandic/sd-extension-steps-animation#3]
I am generating at 320x640, but the output video I get is 80x160. I cant seem to find any options for output scale

Here is the video and generated image for reference

https://user-images.githubusercontent.com/37855219/213933542-182a10bf-4aee-4f8a-94e3-7432fee71866.mp4

![00002-676717913-masterpiece, best quality, animal ears, 1girl, cute, very long hair, pink hair, cat ears, blue eyes, school uniform, school bag,](https://user-images.githubusercontent.com/37855219/213933551-67dd391d-bd97-42c6-8c33-29c509161154.png)

**Comment by vladmandic** [comment]
recent change in main repo makes preview quarter resolution and this extension creates video from preview frames to avoid any additional computational cost.

`settings` -> `live previews` -> `image creation progress preview mode` -> full

i'll add that to docs.
