### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by ghost** [vladmandic/sd-extension-steps-animation#33]
I not understand the diff between the live preview in webui and the image you save in folder. In webui the image are very more clean during the live preview but in folder the image are very malformed comparatively

**Comment by vladmandic** [comment]
Provide some info and proof of that statement or its not actionable at a all.

**Comment by ema7569** [comment]
Just open your eyes to see the live preview and compare with the shit you drop in folder

**Comment by vladmandic** [comment]
closing as no information is provided, i can reopen if information is added.
