### ISSUE TITLE
Enabling Interpolation breaks script with "no such filter: 'fifo'"

### ISSUE THREAD

**Issue by user987098** [vladmandic/sd-extension-steps-animation#34]
Every time I enable any type of Interpolation I get this error and the animation never finishes, it did work the first time I tried it.
I've altered all settings in the script and it changes nothing unless I set Interpolation to none

`returncode=3015096584
ERROR:steps-animation:Steps animation output: Input #0, image2, from 'outputs\txt2img-images\intermediate/%7d-1013823110-why no work.png':
  Duration: 00:00:09.50, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown), 256x256, 2 fps, 2 tbr, 2 tbn
[AVFilterGraph @ 000002c540629cc0] No such filter: 'fifo'
[vost#0:0/libx264 @ 000002c540a81d00] Error initializing a simple filtergraph
Error opening output file outputs\txt2img-images\animation\1013823110-why no work..mp4.
Error opening output files: Filter not found

ERROR:steps-animation:Steps animation: command=ffprobe -hide_banner -print_format json -show_streams "outputs\txt2img-images\animation\1013823110-why no work..mp4" returncode=1
ERROR:steps-animation:Steps animation output: {

}

ERROR:steps-animation:Steps animation output: outputs\txt2img-images\animation\1013823110-why no work..mp4: No such file or directory
`

**Comment by vladmandic** [comment]
that parameters requires that ffmpeg has interpolation functionality built-in. if it doesn't, it wont work. try installing different version of ffmpeg or don't use interpolation - not much else i can do about it here.
in my newer work, i've done native interpolation and video handling, but this is very old extension and i don't plan to rewrite it.
