### ISSUE TITLE
[FEATURE] Added Apple ProRes format for post-production

### ISSUE THREAD

**Issue by masslevel** [vladmandic/sd-extension-steps-animation#5]
Hi @vladmandic.

Thanks for creating this extension!

I was trying to make it work on my Windows installation when you pushed the update 2 days ago that fixed all the path issues. Thank you for that!

I have added a Apple ProRes profile in a very hacky way to my local version. If you want you can add it to Steps Animation. ProRes is a high quality codec that is used in film and post production. It makes sense if you want to further process the source material in a project without loosing quality through strong compression.

It's not meant to offer small file sizes. Because the compression is relatively low, it's great for editing since the decoding requirements are kept to a minimum and allows for smooth video editing timelines.

- I added this to my `steps_animation.py`
`'prores': '-vcodec prores_ks -profile:v 3 -vendor apl0 -bits_per_mb 8000 -pix_fmt yuv422p10le',`
- You would also need to change your `params['outfile']` line to include another `ifel` for the ProRes codec to use `.mov` as a container.
- not all metadata fields are compatible, but the title field is populated in the .mov container.

**Comment by vladmandic** [comment]
its a good suggestion, why not create a PR so you get the credit?  
(if not, i'll add it myself)

**Comment by masslevel** [comment]
thank you! on it.
