### ISSUE TITLE
Unable to parse option value

### ISSUE THREAD

**Issue by DrMacabre** [vladmandic/sd-extension-steps-animation#6]
Hello,

just trying out the extension, i'm getting the same error every time

[image2 demuxer @ 0000019d88e665c0] Unable to parse option value "-0.5" as video rate
[image2 demuxer @ 0000019d88e665c0] Error setting option framerate to value -0.5.
Z:\AI Images\Working Temp\txt2img-images\intermediate/%5d.jpg: Invalid argument

**Comment by vladmandic** [comment]
can you enable the `debug info` in extension settings and paste console log?

**Comment by DrMacabre** [comment]
Hi, thank you, i have set --gradio-debug in the command args of A1111 but it doesn't seem to be debug info, i have no idea where to look, there's nothing in the settings.
As for the version of the extension, it's been installed 10 hours ago so it's probably up to date.

**Comment by DrMacabre** [comment]
hi, thank you, here's the debug info

Data shape for DDIM sampling is (1, 4, 40, 80), eta 0.0                                    | 0/21 [00:00<?, ?it/s]
Running DDIM Sampling with 22 timesteps
DDIM Sampler: 100%|██████████████████████████████████████████████████████████████| 22/22 [00:01<00:00, 14.40it/s]
Running DDIM Sampling with 20 timesteps████████████                              | 21/42 [00:01<00:01, 16.51it/s]
Decoding image: 100%|████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.83it/s]
Steps animation warning: postprocess early call {'current': 0, 'target': 21}█████| 42/42 [00:05<00:00,  4.86it/s]
Steps animation params: {
  "prompt": "a cityscape",
  "negative": "",
  "seed": 2354954396,
  "sampler": "DDIM",
  "cfgscale": 15,
  "steps": 21,
  "current": 0,
  "skip": 5,
  "info": "a cityscape, Steps 21 Sampler DDIM CFG scale 15 Seed 2354954396 Size 640x320 Model hash 8ab08df318 Model 1415FantasyFusionV21 Denoising strength 05 Hires upscale 2 Hires upscaler Latent",
  "model": "1.4-1.5_FantasyFusionV2.1,",
  "embedding": "none",
  "faces": null,
  "timestamp": "20230125223045",
  "inpath": "Z:\\AI Images\\Working Temp\\txt2img-images\\intermediate",
  "outpath": "Z:\\AI Images\\Working Temp\\txt2img-images\\animation",
  "codec": "libx264",
  "duration": 10,
  "interpolation": "mci",
  "loglevel": "info",
  "cli": "ffmpeg -hide_banner -loglevel {loglevel} -hwaccel auto -y -framerate {framerate} -i \"{inpath}/%5d.jpg\" -r {videorate} {preset} {minterpolate} {flags} -metadata title=\"{description}\" -metadata description=\"{info}\" -metadata author=\"stable-diffusion\" -metadata album_artist=\"{author}\" \"{outfile}\"",
  "framerate": -0.5,
  "videorate": 30,
  "author": "https://github.com/vladmandic",
  "preset": "-vcodec libx264 -preset medium -crf 23",
  "flags": "-movflags +faststart",
  "ffmpeg": "c:\\ffmpeg\\bin\\ffmpeg.EXE",
  "minterpolate": "-vf minterpolate=mi_mode=mci,fifo",
  "outfile": "Z:\\AI Images\\Working Temp\\txt2img-images\\animation\\2354954396-a cityscape.mp4",
  "description": "a cityscape | negative  | seed 2354954396 | sampler DDIM | cfgscale 15 | steps 21 | current 0 | model 1.4-1.5_FantasyFusionV2.1, | embedding none | faces None | timestamp 20230125223045 | interpolation mci"
}
Steps animation creating movie sequence: Z:\AI Images\Working Temp\txt2img-images\animation\2354954396-a cityscape.mp4
Steps animation CMD: ffmpeg -hide_banner -loglevel info -hwaccel auto -y -framerate -0.5 -i "Z:\AI Images\Working Temp\txt2img-images\intermediate/%5d.jpg" -r 30 -vcodec libx264 -preset medium -crf 23 -vf minterpolate=mi_mode=mci,fifo -movflags +faststart -metadata title="a cityscape | negative  | seed 2354954396 | sampler DDIM | cfgscale 15 | steps 21 | current 0 | model 1.4-1.5_FantasyFusionV2.1, | embedding none | faces None | timestamp 20230125223045 | interpolation mci" -metadata description="a cityscape, Steps 21 Sampler DDIM CFG scale 15 Seed 2354954396 Size 640x320 Model hash 8ab08df318 Model 1415FantasyFusionV21 Denoising strength 05 Hires upscale 2 Hires upscaler Latent" -metadata author="stable-diffusion" -metadata album_artist="https://github.com/vladmandic" "Z:\AI Images\Working Temp\txt2img-images\animation\2354954396-a cityscape.mp4"
[image2 demuxer @ 00000204def04c00] Unable to parse option value "-0.5" as video rate
[image2 demuxer @ 00000204def04c00] Error setting option framerate to value -0.5.
Z:\AI Images\Working Temp\txt2img-images\intermediate/%5d.jpg: Invalid argument
Steps animation removing 0 files from temp folder: Z:\AI Images\Working Temp\txt2img-images\intermediate
Total progress: 100%|████████████████████████████████████████████████████████████| 42/42 [00:07<00:00,  5.82it/s]

**Comment by vladmandic** [comment]
ok, should be fixed now.

off-topic, `ddim` is probably not the best sampler...

**Comment by DrMacabre** [comment]
thanks. Now it gives another error : 
Steps animation warning: postprocess early call {'current': 0, 'target': 21}42 [00:07<00:00,  4.63it/s]
Save animation error: framerate is zero

when you say DDIM is not the best sampler, you mean for extracting steps animation?

**Comment by vladmandic** [comment]
yes. try with some other sampler. (`ddim` is bad in general, but even worse for extracting steps)
