### ISSUE TITLE
[Feature Request] Upscale to hires fix

### ISSUE THREAD

**Issue by Gazzoo-byte** [vladmandic/sd-extension-steps-animation#7]
If possible can the addon be aware of the hires fix resolution? So far as I can tell it uses the "before fix" resolution and downscales the second pass images to the initial size, it would be nice to have the option to have it upscale the before images instead.

**Comment by vladmandic** [comment]
steps animation works on interim images while hires fix is only applied on the final image.  
appyling hires fix on each interim step would be extremely computationally expensive.
